import { EvidenceRecommendation, ScrutinyRequest, WorkflowCapability } from "../lib";

const pick = (value: Record<string, string> | undefined, locale: string) => value?.[locale] ?? value?.en ?? "";

export function CapabilityBadge({ capability, locale }: { capability: WorkflowCapability; locale: string }) {
  const labels: Record<WorkflowCapability, Record<string, string>> = { SUPPORTED: { en: "Guided workflow", hi: "निर्देशित कार्यप्रवाह" }, PARTIAL_SUPPORT: { en: "Guided with a safe boundary", hi: "सुरक्षित सीमा के साथ मार्गदर्शन" }, EXPLANATION_ONLY: { en: "Explanation and next steps", hi: "व्याख्या और अगले कदम" }, SAFE_STOP: { en: "Safe stop", hi: "सुरक्षित रोक" } };
  return <span className={`capability-badge capability-${capability.toLowerCase()}`}>{labels[capability][locale] ?? labels[capability].en}</span>;
}

export function ContractRequests({ requests, locale }: { requests: ScrutinyRequest[]; locale: string }) {
  if (!requests.length) return null;
  return <section className="universal-section" aria-labelledby="notice-requests-heading"><p className="app-section-label">[ REQUESTS FOUND / {String(requests.length).padStart(2, "0")} ]</p><h2 id="notice-requests-heading" className="question-title">{locale === "hi" ? "विभाग क्या मांग रहा है" : "What the Department is asking"}</h2><div className="universal-request-list">{requests.map((request, index) => <article className="universal-request" key={request.request_id || request.id || index}><div className="universal-request-number">{String(index + 1).padStart(2, "0")}</div><div><p className="app-section-label">{request.category || request.response_section || "Notice request"}</p><h3>{request.what_department_is_asking || request.original_text}</h3>{request.plain_language_explanation && <p className="app-body">{pick(request.plain_language_explanation, locale)}</p>}<details><summary>{locale === "hi" ? "मूल शब्द और स्रोत" : "Original wording and source"}</summary><blockquote>{request.original_text}</blockquote><p className="app-caption">{request.source_location || (request.page_number ? `Page ${request.page_number}` : "Source page not identified")} · {Math.round((request.confidence ?? 0) * 100)}% confidence</p></details></div></article>)}</div></section>;
}

export function ContractEvidence({ evidence, locale }: { evidence: EvidenceRecommendation[]; locale: string }) {
  if (!evidence.length) return null;
  return <section className="universal-section" aria-labelledby="evidence-heading"><p className="app-section-label">[ EVIDENCE / {String(evidence.length).padStart(2, "0")} ]</p><h2 id="evidence-heading" className="question-title">{locale === "hi" ? "क्या तैयार रखना है" : "What you may need"}</h2><div className="universal-evidence-list">{evidence.map((item) => <article className="universal-evidence" key={item.document_id}><div><h3>{pick(item.document_name, locale)}</h3><p>{pick(item.reason, locale)}</p><small>{item.requirement_level === "required" ? (locale === "hi" ? "नोटिस में आवश्यक" : "Required by the notice") : (locale === "hi" ? "संभवतः प्रासंगिक" : "Possibly relevant")} · {item.status.replace(/_/g, " ")}</small></div></article>)}</div></section>;
}

export function CapabilityBoundary({ capability, reason, nextSteps, locale }: { capability: WorkflowCapability; reason: string; nextSteps: string[]; locale: string }) {
  const partial = capability === "PARTIAL_SUPPORT";
  const explanation = capability === "EXPLANATION_ONLY" ? (locale === "hi" ? "Tax Mitra इस संचार को समझाने और अगले कदम दिखाने में मदद कर सकता है, लेकिन अभी सुरक्षित उत्तर तैयार नहीं कर सकता।" : "Tax Mitra can explain this communication and show next steps, but cannot safely prepare the response yet.") : partial ? (locale === "hi" ? "Tax Mitra अनुरोधों को समझने और जानकारी व्यवस्थित करने में मदद कर सकता है, लेकिन कानूनी उत्तर का मसौदा तैयार नहीं करेगा।" : "Tax Mitra can help you understand the requests and organize information, but will not draft an unsupported legal response.") : (locale === "hi" ? "Tax Mitra सुरक्षित सीमा पर रुक गया है और कोई अनुमानित कानूनी निष्कर्ष या उत्तर नहीं बनाया है।" : "Tax Mitra has stopped at a safe boundary and has not invented a legal conclusion or response.");
  const label = capability === "EXPLANATION_ONLY" ? "EXPLANATION ONLY" : partial ? "PARTIAL SUPPORT" : "SAFE STOP";
  return <section className="universal-boundary" role="status"><p className="app-section-label">[ {label} ]</p><h2>{locale === "hi" ? "आपके लिए इसका क्या अर्थ है" : "What this means for you"}</h2><p className="app-body">{explanation}</p><div className="notice-boundary"><strong>{locale === "hi" ? "Tax Mitra ने क्या पाया" : "What we found"}</strong><p>{reason}</p></div><div className="notice-boundary"><strong>{locale === "hi" ? "Tax Mitra क्या कर सकता है" : "What Tax Mitra can help with"}</strong><p>{capability === "EXPLANATION_ONLY" ? (locale === "hi" ? "संचार, अनुरोध और संभावित अगले कदम समझाना।" : "Explain the communication, requests, and grounded next steps.") : (locale === "hi" ? "निकाले गए तथ्यों और अगले कदम को दिखाना।" : "Show grounded facts and supported next steps.")}</p></div><div className="notice-boundary"><strong>{locale === "hi" ? "सुरक्षित सीमा" : "What Tax Mitra cannot safely do"}</strong><p>{explanation}</p></div>{nextSteps.length > 0 && <div><strong>{locale === "hi" ? "अगले कदम" : "Next step"}</strong><ul className="list-disc pl-5 mt-2">{nextSteps.map((step) => <li key={step}>{step}</li>)}</ul></div>}</section>;
}
