"""Personalized document checklists.

Every document explains *why* it is needed, in the citizen's language.
Checklists are derived deterministically from the resolved response path —
never generated by a model.
"""

from __future__ import annotations

from dataclasses import dataclass

Text = dict[str, str]


@dataclass(frozen=True)
class ChecklistItem:
    id: str
    title: Text
    why_needed: Text


_DOCUMENTS: dict[str, ChecklistItem] = {
    "doc_26as": ChecklistItem(
        id="doc_26as",
        title={"en": "Form 26AS / AIS statement", "hi": "फॉर्म 26AS / AIS विवरण"},
        why_needed={
            "en": "Shows the income information the Department received about you, so you can see exactly what it is comparing against.",
            "hi": "यह दिखाता है कि विभाग को आपकी आय के बारे में क्या जानकारी मिली थी, ताकि आप देख सकें कि तुलना किससे की जा रही है।",
        },
    ),
    "doc_itr_extract": ChecklistItem(
        id="doc_itr_extract",
        title={"en": "Relevant pages of your filed tax return", "hi": "आपके दाखिल टैक्स रिटर्न के संबंधित पृष्ठ"},
        why_needed={
            "en": "Proves the income in question was already reported in your return for this assessment year.",
            "hi": "सिद्ध करता है कि विवादित आय इस मूल्यांकन वर्ष के लिए आपके रिटर्न में पहले से दर्ज थी।",
        },
    ),
    "doc_bank_statement": ChecklistItem(
        id="doc_bank_statement",
        title={"en": "Bank statement for the relevant period", "hi": "संबंधित अवधि का बैंक विवरण"},
        why_needed={
            "en": "Shows whether the income in question was actually credited to your account.",
            "hi": "दिखाता है कि विवादित आय वास्तव में आपके खाते में आई थी या नहीं।",
        },
    ),
    "doc_interest_certificate": ChecklistItem(
        id="doc_interest_certificate",
        title={"en": "Interest certificate / Form 16A from the payer", "hi": "भुगतानकर्ता से ब्याज प्रमाणपत्र / फॉर्म 16A"},
        why_needed={
            "en": "Confirms the exact amount the payer reported paying you, and any tax they deducted.",
            "hi": "पुष्टि करता है कि भुगतानकर्ता ने आपको कितनी राशि की सूचना दी थी और कोई कर काटा था या नहीं।",
        },
    ),
    "doc_computation": ChecklistItem(
        id="doc_computation",
        title={"en": "Computation of total income", "hi": "कुल आय की गणना"},
        why_needed={
            "en": "A simple sheet showing your income heads and totals, so the response is easy for the Department to verify.",
            "hi": "आपकी आय के स्रोतों और कुल राशि की सरल तालिका, ताकि विभाग के लिए सत्यापन आसान हो।",
        },
    ),
    "doc_ais_download": ChecklistItem(
        id="doc_ais_download",
        title={"en": "Download your AIS statement (how-to)", "hi": "अपना AIS विवरण डाउनलोड करें (कैसे करें)"},
        why_needed={
            "en": "You don't have a supporting document yet — start by downloading the Annual Information Statement from the e-Filing portal.",
            "hi": "आपके पास अभी समर्थन दस्तावेज़ नहीं है — पहले e-Filing पोर्टल से वार्षिक सूचना विवरण (AIS) डाउनलोड कीजिए।",
        },
    ),
    "doc_payer_confirmation": ChecklistItem(
        id="doc_payer_confirmation",
        title={"en": "Written confirmation from the payer", "hi": "भुगतानकर्ता से लिखित पुष्टि"},
        why_needed={
            "en": "If you're not sure about the income, ask the bank or payer to confirm what they reported and to whom.",
            "hi": "यदि आय के बारे में पक्का नहीं हैं, तो बैंक या भुगतानकर्ता से पूछिए कि उन्होंने क्या और किसके लिए रिपोर्ट किया था।",
        },
    ),
}


def checklist_for(doc_ids: tuple[str, ...]) -> list[ChecklistItem]:
    """Resolve document ids to items. Unknown ids raise — a checklist must
    never silently shrink because someone renamed a document."""
    unknown = [i for i in doc_ids if i not in _DOCUMENTS]
    if unknown:
        raise KeyError(f"Unknown checklist document ids: {unknown}")
    return [_DOCUMENTS[i] for i in doc_ids]


def known_document_ids() -> frozenset[str]:
    return frozenset(_DOCUMENTS)
