import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useI18n } from "../i18n";
import { api, Question, ResolveResult, formatINR, OFFICIAL_EFILING_PORTAL_URL, store } from "../lib";
import { Card, PrimaryButton, Stepper } from "../components";

type Phase = "questions" | "checklist" | "draft" | "review" | "final";

export default function Journey() {
  const { id } = useParams<{ id: string }>();
  const { t, locale } = useI18n();
  const [phase, setPhase] = useState<Phase>("questions");
  const [questions, setQuestions] = useState<Question[] | null>(null);
  const [notice, setNotice] = useState<Awaited<ReturnType<typeof api.notice>> | null>(null);
  const [qIndex, setQIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>(() => (id ? store.answers(id) : {}));
  const [result, setResult] = useState<ResolveResult | null>(null);
  const [draft, setDraft] = useState("");
  const [copied, setCopied] = useState(false);
  const [checklistState, setChecklistState] = useState<Record<string, boolean>>({});

  const handleChecklistToggle = (key: string) => {
    setChecklistState(prev => ({ ...prev, [key]: !prev[key] }));
  };

  useEffect(() => {
    if (!id) return;
    api.questions(id, locale).then((r) => setQuestions(r.questions)).catch(() => setQuestions([]));
    api.notice(id).then(setNotice).catch(() => setNotice(null));
  }, [id, locale]);

  const answer = (optionId: string) => {
    if (!id || !questions || questions.length === 0) return;
    const q = questions[qIndex];
    const next = { ...answers, [q.id]: optionId };
    setAnswers(next);
    store.setAnswers(id, next);
    if (qIndex + 1 < questions.length) {
      setQIndex(qIndex + 1);
    } else {
      api.resolve(id, next).then((r) => {
        setResult(r);
        setDraft(r.draft ?? "");
        setPhase("checklist");
      });
    }
  };

  const downloadAsTxt = () => {
    if (!draft || !id) return;
    const blob = new Blob([draft], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `tax-mitra-response-${id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAsMarkdown = () => {
    if (!draft || !id || !notice) return;
    const md = `# Tax Mitra Response Draft

**Notice:** ${notice.section} · ${notice.title[locale] ?? notice.title.en}
**Assessment Year:** ${notice.assessment_year}

---

${draft}
`;
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `tax-mitra-response-${id}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAsPdf = () => {
    if (!draft || !id || !notice) return;
    const printContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Tax Mitra Response Draft</title>
  <style>
    body { font-family: 'Times New Roman', serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
    h1 { border-bottom: 2px solid #333; padding-bottom: 10px; }
    .meta { color: #666; margin-bottom: 30px; }
    .draft { white-space: pre-wrap; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <h1>Tax Mitra Response Draft</h1>
  <div class="meta">
    <p><strong>Notice:</strong> ${notice.section} · ${notice.title[locale] ?? notice.title.en}</p>
    <p><strong>Assessment Year:</strong> ${notice.assessment_year}</p>
  </div>
  <div class="draft">${draft}</div>
  <div class="footer">
    <p>This draft was generated by Tax Mitra, an independent prototype and is not affiliated with or endorsed by the Income Tax Department or Government of India.</p>
    <p>Tax Mitra does not submit anything on your behalf. You must submit this response yourself through the official Income Tax e-Filing portal.</p>
  </div>
</body>
</html>`;
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const stepperFor = (p: Phase): 0 | 1 | 2 | 3 =>
    p === "questions" ? 1 : p === "checklist" ? 2 : p === "draft" ? 2 : 3;

  if (!id) return null;
  if (!questions) return <div className="app-page"><div className="app-loading">PREPARING GUIDED QUESTIONS</div></div>;
  const q = questions[qIndex];
  const positionLabel = (pos?: string) =>
    pos === "agree" ? "AGREE" : pos === "disagree" ? "DISAGREE" : "NOT SURE";

  return (
    <div className="app-page">
      <Stepper current={stepperFor(phase)} />

      {phase === "questions" && (
        <div>
          <h1 className="app-title">{t("j.qTitle")}</h1>
          <p className="text-sm text-stone-600 mt-1 mb-5">{t("j.qHelp")}</p>
          {q && (
            <Card>
              <div className="question-progress"><span>QUESTION {String(qIndex + 1).padStart(2, "0")}</span><span>{qIndex + 1} / {questions.length}</span></div>
              <div className="question-meter" aria-hidden="true"><i style={{ width: `${((qIndex + 1) / questions.length) * 100}%` }} /></div>
              <h2 className="question-title">{q.text}</h2>
              {q.help && <p className="text-sm text-stone-500 mt-2">{q.help}</p>}
              <div className="mt-5 grid gap-2">
                {q.options.map((o) => (
                  <button
                    key={o.id}
                    onClick={() => answer(o.id)}
                    className={`journey-answer${answers[q.id] === o.id ? " is-selected" : ""}`}
                  >
                    {o.label}
                  </button>
                ))}
              </div>
            </Card>
          )}
          {qIndex > 0 ? (
            <button onClick={() => setQIndex(qIndex - 1)} className="app-back">
              ← {t("j.back")}
            </button>
          ) : (
            <Link to={`/notices/${id}`} className="app-back">← {t("j.back")}</Link>
          )}
        </div>
      )}

      {phase === "checklist" && result?.checklist && (
        <div>
          <h1 className="app-title">{t("j.checklistTitle")}</h1>
          <p className="text-sm text-stone-600 mt-1 mb-4">{t("j.checklistSub")}</p>
          <Card className="mb-4 workflow-guidance">
            <p className="app-section-label">[ YOUR GUIDED PATH ]</p>
            <h2 className="text-xl font-medium leading-snug mb-2">{result.path?.headline[locale] ?? result.path?.headline.en}</h2>
            <p className="app-body text-sm leading-relaxed">{result.path?.guidance[locale] ?? result.path?.guidance.en}</p>
          </Card>
          <p className="app-section-label mb-3">[ EVIDENCE YOU MAY NEED ]</p>
          <div className="checklist-list">
            {result.checklist.map((item, index) => (
              <Card key={item.id}>
                <p className="checklist-title"><span>{String(index + 1).padStart(2, "0")}</span>{item.title[locale] ?? item.title.en}</p>
                <details><summary>{t("j.why")} ↓</summary><p className="app-body">{item.why_needed[locale] ?? item.why_needed.en}</p></details>
              </Card>
            ))}
          </div>
          <div className="mt-6 flex flex-wrap items-center gap-3">
            <PrimaryButton onClick={() => setPhase("draft")}>{t("j.next")} →</PrimaryButton>
            <button className="app-back !mt-0" onClick={() => setPhase("questions")}>← {t("j.back")}</button>
          </div>
        </div>
      )}

      {phase === "draft" && (
        <div>
          <h1 className="app-title">{t("j.draftTitle")}</h1>
          <p className="text-sm text-stone-600 mt-1 mb-4">{t("j.draftSub")}</p>
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onBlur={() => store.setDraft(id, draft)}
            placeholder={t("j.draftPlaceholder")}
            rows={14}
            className="w-full border border-stone-300 focus:border-blue-600 p-4 text-sm leading-relaxed outline-none"
          />
          <div className="mt-4 flex flex-wrap items-center gap-3">
            <PrimaryButton
              onClick={() => {
                store.setDraft(id, draft);
                setPhase("review");
              }}
            >
              {t("j.acceptDraft")} →
            </PrimaryButton>
            <button className="app-back !mt-0" onClick={() => setPhase("checklist")}>← {t("j.back")}</button>
          </div>
        </div>
      )}

      {phase === "review" && result?.path && (
        <div>
          <h1 className="app-title">{t("j.reviewTitle")}</h1>
          <Card className="my-4">
            <dl className="text-sm divide-y divide-stone-100">
              <div className="py-2 flex justify-between gap-4">
                <dt className="text-stone-500">{t("j.reviewIssue")}</dt>
                <dd className="font-semibold text-right">{notice ? `${notice.section} · ${notice.title[locale] ?? notice.title.en}` : "—"}</dd>
              </div>
              <div className="py-2 flex justify-between gap-4">
                <dt className="text-stone-500">{t("j.reviewAmount")}</dt>
                <dd className="font-semibold">{notice ? formatINR(notice.amount_in_question) : "—"}</dd>
              </div>
              <div className="py-2 flex justify-between gap-4">
                <dt className="text-stone-500">{t("j.reviewPosition")}</dt>
                <dd className="font-semibold">{positionLabel(result.path.position)}</dd>
              </div>
              <div className="py-2 flex justify-between gap-4">
                <dt className="text-stone-500">{t("j.reviewDocs")}</dt>
                <dd className="font-semibold">{result.checklist?.length ?? 0}</dd>
              </div>
              <div className="py-2 flex justify-between gap-4">
                <dt className="text-stone-500">{t("j.reviewDeadline")}</dt>
                <dd className="font-semibold">{result.deadline?.due_date ?? "—"}</dd>
              </div>
            </dl>
          </Card>
          <p className="text-sm text-stone-600 mb-4">{t("j.reviewNote")}</p>
          <div className="flex flex-wrap items-center gap-3">
            <PrimaryButton onClick={() => setPhase("final")}>{t("j.next")} →</PrimaryButton>
            <button className="app-back !mt-0" onClick={() => setPhase("draft")}>← {t("j.back")}</button>
          </div>
        </div>
      )}

      {phase === "final" && result?.official_step && (
        <div>
          <p className="app-eyebrow">[ TM / ACT / 04 ]</p>
          <h1 className="app-title">{t("j.finalTitle")}</h1>
          <p className="app-lead">{t("j.finalLead")}</p>
          
          <div className="app-content-spacing">
            <p className="app-section-label">{t("j.actionPlan")}</p>
            
            <div className="action-timeline">
              <div className="action-step">
                <span className="action-number">01</span>
                <div>
                  <h3>{t("j.act01")}</h3>
                  <p>{t("j.act01Desc")}</p>
                </div>
              </div>
              
              <div className="action-step">
                <span className="action-number">02</span>
                <div>
                  <h3>{t("j.act02")}</h3>
                  <p>{t("j.act02Desc")}</p>
                  {result.checklist && result.checklist.length > 0 && (
                    <ul className="action-checklist">
                      {result.checklist.map((c) => (
                        <li key={c.id}>• {c.title[locale] ?? c.title.en}</li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>
              
              <div className="action-step">
                <span className="action-number">03</span>
                <div>
                  <h3>{t("j.act03")}</h3>
                  <p>{t("j.act03Desc")}</p>
                </div>
              </div>
              
              <div className="action-step">
                <span className="action-number">04</span>
                <div>
                  <h3>{t("j.act04")}</h3>
                  <p className="font-mono text-sm text-stone-600">{t("j.portalNav")}</p>
                  {notice && (
                    <div className="action-meta">
                      <p><strong>{t("scrutiny.notice")}:</strong> {notice.section}</p>
                      <p><strong>{t("dash.ay")}:</strong> {notice.assessment_year}</p>
                    </div>
                  )}
                </div>
              </div>
              
              <div className="action-step">
                <span className="action-number">05</span>
                <div>
                  <h3>{t("j.act05")}</h3>
                  <p>{notice?.section?.replace(/\s/g, "").startsWith("142(1)") ? t("j.act05Desc142") : t("j.act05Desc143")}</p>
                </div>
              </div>
              
              <div className="action-step">
                <span className="action-number">06</span>
                <div>
                  <h3>{t("j.act06")}</h3>
                  <p>{t("j.act06Desc")}</p>
                </div>
              </div>
              
              <div className="action-step">
                <span className="action-number">07</span>
                <div>
                  <h3>{t("j.act07")}</h3>
                  <p>{t("j.act07Desc")}</p>
                </div>
              </div>
            </div>

            <div className="checklist-visual my-6">
              <p className="app-section-label">{t("j.beforeSubmit")}</p>
              <div className="checklist-items">
                <label className="checklist-item">
                  <input
                    type="checkbox"
                    checked={checklistState.check01 || false}
                    onChange={() => handleChecklistToggle('check01')}
                  />
                  <span>{t("j.check01")}</span>
                </label>
                <label className="checklist-item">
                  <input
                    type="checkbox"
                    checked={checklistState.check02 || false}
                    onChange={() => handleChecklistToggle('check02')}
                  />
                  <span>{t("j.check02")}</span>
                </label>
                <label className="checklist-item">
                  <input
                    type="checkbox"
                    checked={checklistState.check03 || false}
                    onChange={() => handleChecklistToggle('check03')}
                  />
                  <span>{t("j.check03")}</span>
                </label>
                <label className="checklist-item">
                  <input
                    type="checkbox"
                    checked={checklistState.check04 || false}
                    onChange={() => handleChecklistToggle('check04')}
                  />
                  <span>{t("j.check04")}</span>
                </label>
                <label className="checklist-item">
                  <input
                    type="checkbox"
                    checked={checklistState.check05 || false}
                    onChange={() => handleChecklistToggle('check05')}
                  />
                  <span>{t("j.check05")}</span>
                </label>
              </div>
            </div>

            <div className="value-summary my-6">
              <p className="app-section-label">{t("j.whatTaxMitraDid")}</p>
              <ul className="value-list">
                <li>{t("j.help01")}</li>
                <li>{t("j.help02")}</li>
                <li>{t("j.help03")}</li>
                <li>{t("j.help04")}</li>
                <li>{t("j.help05")}</li>
                <li>{t("j.help06")}</li>
              </ul>
              <p className="app-body mt-2 italic">{t("j.yourSubmission")}</p>
            </div>

            <Card className="my-4">
              <p className="app-section-label">[ {t("j.downloadDraft")} ]</p>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-3">
                <button onClick={downloadAsTxt} className="app-primary">
                  {t("j.downloadTxt")}
                </button>
                <button onClick={downloadAsMarkdown} className="app-primary">
                  {t("j.downloadMd")}
                </button>
                <button onClick={downloadAsPdf} className="app-primary">
                  {t("j.downloadPdf")}
                </button>
              </div>
              <button
                onClick={() => {
                  navigator.clipboard?.writeText(draft);
                  setCopied(true);
                }}
                className="text-sm text-stone-600 underline py-2 mt-3"
              >
                {copied ? t("j.finalCopied") : t("j.finalCopy")}
              </button>
            </Card>

            <div className="notice-boundary mb-4">
              <p className="app-section-label">[ IMPORTANT ]</p>
              <p className="app-body font-medium">{t("j.finalBoundary")}</p>
              <p className="app-body mt-2">{t("j.finalInstruction")}</p>
            </div>

            <div className="grid gap-2">
              <a
                href={OFFICIAL_EFILING_PORTAL_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="app-primary text-center"
              >
                {t("j.continuePortal")}
              </a>
            </div>
            <div className="mt-6 flex flex-wrap items-center justify-center gap-5">
              <button className="app-back !mt-0" onClick={() => setPhase("review")}>← {t("j.back")}</button>
              <Link to="/notices" className="text-sm text-stone-500 underline">
                {t("j.restart")}
              </Link>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
