import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useI18n } from "../i18n";
import { api, ApiError, NoticeCard, OFFICIAL_EFILING_PORTAL_URL, ScrutinyQuestion, ScrutinyRequestsResult, ScrutinyResolveResult, store, verifiedIncomeTaxUrl } from "../lib";
import { Card, PrimaryButton, Stepper } from "../components";

type Stage = "requests" | "confirm" | "questions" | "result" | "draft" | "review" | "final" | "refusal";
const text = (value: Record<string, string> | undefined, locale: string) => value?.[locale] ?? value?.en ?? "";

function ErrorState({ error, retry }: { error: ApiError | Error; retry: () => void }) {
  const { locale, t } = useI18n();
  const message = error instanceof ApiError && error.status === 404 ? t("scrutiny.error404") : error instanceof ApiError && error.status === 429 ? t("scrutiny.error429") : error instanceof ApiError && error.status === 503 ? t("scrutiny.error503") : t("scrutiny.errorGeneric");
  return <div className="app-empty"><p className="app-section-label">[ {t("scrutiny.errorLabel")} ]</p><p>{message}</p><button className="app-primary mt-5" onClick={retry}>{t("scrutiny.retry")}</button></div>;
}

export default function Scrutiny() {
  const { id = "" } = useParams();
  const { locale, t } = useI18n();
  const restored = store.scrutinyStage(id) as Stage;
  const isUploaded = store.uploadedNoticeId() === id;
  const [stage, setStageState] = useState<Stage>(restored === "questions" && !store.extractionConfirmed(id) ? "requests" : restored);
  const [notice, setNotice] = useState<NoticeCard | null>(null);
  const [data, setData] = useState<ScrutinyRequestsResult | null>(null);
  const [questions, setQuestions] = useState<ScrutinyQuestion[]>([]);
  const [answers, setAnswers] = useState<Record<string, string>>(() => store.answers(id));
  const [index, setIndex] = useState(0);
  const [result, setResult] = useState<ScrutinyResolveResult | null>(null);
  const [draft, setDraft] = useState(() => store.draft(id) ?? "");
  const [error, setError] = useState<Error | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [finalCopied, setFinalCopied] = useState(false);
  const setStage = (next: Stage) => { setStageState(next); store.setScrutinyStage(id, next); window.scrollTo({ top: 0, behavior: "smooth" }); };

  const downloadDraft = () => {
    const blob = new Blob([draft], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `tax-mitra-response-${id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAsMarkdown = () => {
    if (!draft || !id || !notice) return;
    const md = `# Tax Mitra Response Draft

**Notice:** ${notice.section} · ${notice.title[locale] ?? notice.title.en}
**Assessment Year:** ${notice.assessment_year}

---

${draft}
`;
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `tax-mitra-response-${id}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAsPdf = () => {
    if (!draft || !id || !notice) return;
    const printContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Tax Mitra Response Draft</title>
  <style>
    body { font-family: 'Times New Roman', serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
    h1 { border-bottom: 2px solid #333; padding-bottom: 10px; }
    .meta { color: #666; margin-bottom: 30px; }
    .draft { white-space: pre-wrap; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <h1>Tax Mitra Response Draft</h1>
  <div class="meta">
    <p><strong>Notice:</strong> ${notice.section} · ${notice.title[locale] ?? notice.title.en}</p>
    <p><strong>Assessment Year:</strong> ${notice.assessment_year}</p>
  </div>
  <div class="draft">${draft}</div>
  <div class="footer">
    <p>This draft was generated by Tax Mitra, an independent civic prototype.</p>
    <p>Tax Mitra does not submit anything on your behalf. You must submit this response yourself through the official Income Tax e-Filing portal.</p>
  </div>
</body>
</html>`;
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const load = () => {
    const controller = new AbortController(); setLoading(true); setError(null);
    Promise.all([
      isUploaded ? Promise.resolve(null) : api.notice(id),
      api.scrutinyRequests(id, locale, true, controller.signal),
    ])
      .then(([n, r]) => { setNotice(n); setData(r); setLoading(false); })
      .catch((e) => { if (e.name !== "AbortError") { setError(e); setLoading(false); } });
    return () => controller.abort();
  };
  useEffect(load, [id, locale]);

  const confirm = async () => {
    setLoading(true); setError(null);
    try { const response = await api.scrutinyQuestions(id, locale, true); store.setExtractionConfirmed(id, true); setQuestions(response.questions); setIndex(Math.max(0, response.questions.findIndex(q => !answers[q.id]))); setStage("questions"); }
    catch (e) { setError(e as Error); }
    finally { setLoading(false); }
  };
  const reject = async () => {
    setLoading(true);
    try { setResult(await api.resolveScrutiny(id, {}, false)); setStage("refusal"); }
    catch (e) { setError(e as Error); }
    finally { setLoading(false); }
  };
  const answer = async (value: string) => {
    const q = questions[index]; const next = { ...answers, [q.id]: value }; setAnswers(next); store.setAnswers(id, next);
    if (index < questions.length - 1) { setIndex(index + 1); return; }
    setLoading(true); setError(null);
    try { const resolved = await api.resolveScrutiny(id, next, true); setResult(resolved); setDraft(store.draft(id) ?? resolved.draft ?? ""); setStage("result"); }
    catch (e) { setError(e as Error); }
    finally { setLoading(false); }
  };
  const ensureQuestions = async () => { if (!questions.length) { const r = await api.scrutinyQuestions(id, locale, true); setQuestions(r.questions); } setStage("questions"); };

  if (loading && !data) return <div className="app-page"><div className="app-loading">{t("scrutiny.loading")}</div></div>;
  if (error && !data) return <div className="app-page"><ErrorState error={error} retry={load} />{isUploaded ? <Link to="/upload" className="app-primary mt-5">{t("scrutiny.newPdf")}</Link> : <Link to="/notices" className="app-back">← {t("j.back")}</Link>}</div>;
  if (!data || (!notice && !isUploaded)) return null;
  const requests = data.requests ?? [];
  const q = questions[index];
  const step = stage === "requests" || stage === "confirm" ? 0 : stage === "questions" ? 1 : stage === "result" || stage === "draft" ? 2 : 3;

  return <div className="app-page scrutiny-page">
    <Stepper current={step} />
    {error && <div className="mb-5"><ErrorState error={error} retry={() => setError(null)} /></div>}

    {stage === "requests" && <>
      <p className="app-eyebrow">[ TM / SCRUTINY / REQUESTS ]</p><h1 className="app-title">{t("scrutiny.title")}</h1>
      <div className="scrutiny-meta"><span>{notice?.section ?? "142(1)"}</span>{notice?.assessment_year && <span>AY {notice.assessment_year}</span>}{notice?.official_reference && <span>{notice.official_reference}</span>}{notice?.due_date && <span>{notice.due_date}</span>}</div>
      <p className="app-lead">{t("scrutiny.lead", {count: String(requests.length)})}</p>
      <p className="request-count">{String(requests.length).padStart(2,"0")} {t("scrutiny.count")}</p>
      <div className="document-requests">{requests.map((r, i) => <details className="document-request" key={r.id} open={i===0}><summary><span>{String(i+1).padStart(2,"0")}</span><strong>{text(r.plain_language_explanation,locale) || r.response_section}</strong><i>{t("j.next")}</i></summary><div className="document-request-body"><p className="request-label">{t("scrutiny.labelAsking")}</p><p className="request-explanation">{text(r.plain_language_explanation,locale)}</p>{r.required_evidence.length>0&&<><p className="request-label">{t("scrutiny.labelNeed")}</p><ul className="evidence-list-simple">{r.required_evidence.map((e,j)=><li key={j}>{text(e,locale)}</li>)}</ul></>}<details className="original-source"><summary>{t("scrutiny.viewOriginal")}</summary><div className="official-wording"><b>{t("scrutiny.officialWording")}</b><blockquote>{r.original_text}</blockquote></div></details><details className="verification-details"><summary>{t("scrutiny.howUnderstood")}</summary><div className="verification-content"><div className="verification-row"><span>{t("scrutiny.responseSection")}</span><b>{r.response_section}</b></div><div className="verification-row"><span>{t("scrutiny.extractionConfidence")}</span><b>{Math.round(r.confidence*100)}%</b></div><div className="verification-row"><span>{t("scrutiny.groundingConfidence")}</span><b>{r.grounding.method} {Math.round(r.grounding.confidence*100)}%</b></div>{r.why_required&&<div className="verification-row"><span>{t("scrutiny.whyRequired")}</span><p>{text(r.why_required,locale)}</p></div>}{r.warnings.length>0&&<div className="verification-warnings">{r.warnings.map((warning,j)=><p key={j}>{warning}</p>)}</div>}{r.citations.length>0&&<div className="verification-citations"><p className="verification-label">{t("scrutiny.sources")}</p>{r.citations.map(c=><a key={c.id} href={c.official_url} target="_blank" rel="noreferrer">{c.source_name} · {c.section} ↗</a>)}</div>}</div></details></div></details>)}</div>
      <div className="notice-boundary"><p className="app-section-label">[ {isUploaded ? t("scrutiny.confirmedExtraction") : t("scrutiny.humanConfirmation")} ]</p><p className="app-body">{isUploaded ? t("scrutiny.confirmedText") : t("scrutiny.syntheticText")}</p></div>
      <div className="flex flex-wrap items-center gap-3"><PrimaryButton onClick={isUploaded ? ensureQuestions : () => setStage("confirm")}>{isUploaded ? t("scrutiny.checkRecords") : t("scrutiny.confirmList")} →</PrimaryButton><Link className="app-back !mt-0" to={isUploaded ? "/upload" : `/notices/${id}`}>← {t("j.back")}</Link></div>
    </>}

    {stage === "confirm" && <Card className="confirmation-card app-dots"><p className="app-section-label">[ {t("scrutiny.checkpoint")} ]</p><h1>{t("scrutiny.confirmTitle")}</h1><p className="app-body">{t("scrutiny.confirmSub", {count: String(requests.length)})}</p><div className="confirmation-actions"><PrimaryButton onClick={confirm}>{t("scrutiny.yesCorrect")} →</PrimaryButton><button onClick={reject}>{t("scrutiny.somethingWrong")}</button></div><button className="app-back" onClick={() => setStage("requests")}>← {t("j.back")}</button></Card>}

    {stage === "questions" && q && <><p className="app-eyebrow">[ {t("scrutiny.evidenceCheck")} / {String(index + 1).padStart(2, "0")} ]</p><h1 className="app-title">{t("scrutiny.questionTitle")}</h1><Card><div className="question-progress"><span>{t("scrutiny.questionProgress")} {index + 1}</span><span>{index + 1} / {questions.length}</span></div><div className="question-meter"><i style={{width:`${((index + 1) / questions.length) * 100}%`}} /></div><h2 className="question-title">{q.text}</h2><p className="app-body mt-3">{q.help}</p><div className="answer-grid">{q.options.map(o => <button className={answers[q.id] === o.id ? "is-selected" : ""} key={o.id} onClick={() => answer(o.id)}>{o.label}<span>→</span></button>)}</div></Card><button className="app-back" onClick={() => index > 0 ? setIndex(index - 1) : setStage("requests")}>← {t("j.back")}</button></>}

    {stage === "result" && result?.path && <><p className="app-eyebrow">[ {t("scrutiny.deterministicResult")} / {result.path.path_id.toUpperCase()} ]</p><h1 className="app-title">{text(result.path.headline, locale)}</h1>{result.path.professional_help_recommended && <div className="notice-boundary"><p className="app-section-label">[ {t("scrutiny.professionalReview")} ]</p><p className="app-body">{t("scrutiny.professionalText")}</p></div>}<div className="checklist-list">{result.checklist?.map(item => <Card key={item.id}><p className="checklist-title"><span>{item.status.toUpperCase()}</span>{text(item.title, locale)}</p><ul className="evidence-list">{item.required_evidence.map((e,i)=><li key={i}>{text(e,locale)}</li>)}</ul></Card>)}</div><div className="flex flex-wrap gap-3"><PrimaryButton onClick={() => setStage("draft")}>{t("scrutiny.resultTitle")} →</PrimaryButton><button className="app-back !mt-0" onClick={ensureQuestions}>← {t("scrutiny.changeAnswers")}</button></div></>}

    {stage === "draft" && <><p className="app-eyebrow">[ {t("scrutiny.responsePackage")} / {t("scrutiny.draft")} ]</p><h1 className="app-title">{t("j.draftTitle")}</h1><p className="app-lead mb-5">{t("j.draftSub")}</p><textarea className="scrutiny-draft" rows={20} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>store.setDraft(id,draft)} /><div className="flex flex-wrap items-center gap-3"><PrimaryButton onClick={()=>{store.setDraft(id,draft);setStage("review")}}>{t("j.acceptDraft")} →</PrimaryButton><button onClick={downloadDraft}>{t("scrutiny.downloadDraft")}</button><button onClick={async()=>{await navigator.clipboard.writeText(draft);setCopied(true);setTimeout(()=>setCopied(false),2000)}}>{copied ? t("scrutiny.copied") : t("scrutiny.copyDraft")}</button><button className="app-back !mt-0" onClick={()=>setStage("result")}>← {t("j.back")}</button></div></>}

    {stage === "review" && result && <><p className="app-eyebrow">[ {t("scrutiny.finalReview")} / {t("scrutiny.humanApproval")} ]</p><h1 className="app-title">{t("j.reviewTitle")}</h1><div className="review-grid"><Card><p className="app-section-label">[ {t("scrutiny.coverage")} ]</p>{result.checklist?.map(x=><p key={x.id} className="review-row"><span>{text(x.title,locale)}</span><b>{x.status.toUpperCase()}</b></p>)}</Card><Card className="deadline-card"><p className="app-section-label">[ {t("scrutiny.responseDeadline")} ]</p><strong>{result.deadline?.due_date ?? "—"}</strong><p>{t("scrutiny.reviewDateText")}</p></Card></div><div className="notice-boundary"><p className="app-section-label">[ {t("scrutiny.reviewLabel")} ]</p><p className="app-body">{t("scrutiny.reviewText")}</p></div><div className="flex flex-wrap items-center gap-3"><PrimaryButton onClick={()=>setStage("final")}>{t("scrutiny.continueHandoff")} →</PrimaryButton><button className="app-back !mt-0" onClick={()=>setStage("draft")}>← {t("j.back")}</button></div></>}

    {stage === "final" && result?.official_step && <><p className="app-eyebrow">[ {t("scrutiny.officialHandoff")} / 04 ]</p><h1 className="app-title">{t("j.finalTitle")}</h1><p className="app-lead">{t("j.finalLead")}</p><Card className="app-dots"><p className="app-section-label">[ {t("scrutiny.whatToDo")} ]</p><h2 className="text-2xl font-medium">{text(result.official_step.label,locale)}</h2><p className="deadline-inline">{result.deadline?.due_date}</p></Card><div className="value-summary"><p className="app-section-label">[ {t("scrutiny.valueSummary")} ]</p><ul className="value-list"><li>✓ {t("scrutiny.valueRead")}</li><li>✓ {t("scrutiny.valueIdentified")}</li><li>✓ {t("scrutiny.valueBroke", {count: String(requests.length)})}</li><li>✓ {t("scrutiny.valueChecked")}</li><li>✓ {t("scrutiny.valueVerification")}</li><li>✓ {t("scrutiny.valueDraft")}</li><li>✓ {t("scrutiny.valueGuided")}</li></ul></div><Card className="my-4"><p className="app-section-label">[ {t("j.downloadDraft")} ]</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-3"><button onClick={downloadDraft} className="app-primary">{t("j.downloadTxt")}</button><button onClick={downloadAsMarkdown} className="app-primary">{t("j.downloadMd")}</button><button onClick={downloadAsPdf} className="app-primary">{t("j.downloadPdf")}</button></div><button onClick={async()=>{await navigator.clipboard.writeText(draft);setFinalCopied(true);setTimeout(()=>setFinalCopied(false),2000)}} className="text-sm text-stone-600 underline py-2 mt-3">{finalCopied ? t("scrutiny.copied") : t("scrutiny.copyDraft")}</button></Card><div className="notice-boundary"><p className="app-section-label">[ {t("scrutiny.readyStep")} ]</p><p className="app-body font-medium">{t("scrutiny.readyText")}</p><p className="app-body mt-2">{t("j.finalBoundary")}</p><p className="app-body mt-2">{t("j.finalInstruction")}</p></div><div className="final-actions"><a className="app-primary" href={OFFICIAL_EFILING_PORTAL_URL} target="_blank" rel="noopener noreferrer">{t("j.continuePortal")}</a></div><button className="app-back" onClick={()=>setStage("review")}>← {t("j.back")}</button></>}

    {stage === "refusal" && result && <><p className="app-eyebrow">[ {t("scrutiny.safeStop")} ]</p><h1 className="app-title">{text(result.headline,locale)}</h1><div className="refusal-layout"><Card><p className="app-section-label">[ {t("scrutiny.refusalWhy")} ]</p><p className="app-body">{text(result.why,locale)}</p></Card><Card><p className="app-section-label">[ {t("scrutiny.refusalSuggestion")} ]</p><p className="app-body">{text(result.suggestion,locale)}</p></Card><Card>{result.official_links?.map(link=><a key={link.url} className="app-text-action block mb-3" href={verifiedIncomeTaxUrl(link.url)} target="_blank" rel="noopener noreferrer">{text(link.label,locale)} ↗</a>)}</Card></div><button className="app-back" onClick={()=>setStage("requests")}>← {t("scrutiny.reviewAgain")}</button></>}
  </div>;
}
